# Generated by Django 3.1 on 2021-07-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_auto_20210703_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='organisation',
        ),
    ]
