# Generated by Django 3.2.3 on 2021-07-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_auto_20210707_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='Lead_status',
            field=models.CharField(choices=[('Crucial', 'Crucial'), ('Not Crucial', 'Not Crucial'), ('Normal', 'Normal')], default='Normal', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='spendings',
            field=models.IntegerField(default=0),
        ),
    ]
