# Generated by Django 3.2.3 on 2021-07-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_auto_20210707_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
