# Generated by Django 3.2.3 on 2021-07-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_agent_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=20)),
                ('task_state', models.BooleanField(default=False)),
            ],
        ),
    ]
