# Generated by Django 3.2.3 on 2021-07-08 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_state',
            new_name='done',
        ),
    ]
