# Generated by Django 3.2.3 on 2021-07-08 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_rename_task_state_task_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='Task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Agent', to='leads.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.agent'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_descrption',
            field=models.CharField(default='None', max_length=20),
            preserve_default=False,
        ),
    ]
